### PR TITLE
Update intel_backlight.c

### PR DESCRIPTION
**Pull request by maurizio-emmex**
Added: help message, option -n to show only brightness percent level as number, option -r to set the brightness hardware register directly, check for unsupported hardware.

### CODE REVIEW

**Comment by maurizio-emmex** [comment]
I have made some changes. Please review.

**Comment by grembo** [comment]
Hi Maurizio,

Thanks for your pull request. It looks good, but there's one issue: Right now, intel-backlight.c is just copied from intel's GPU tools. So it might make more sense to get your patch into intel-gpu-tools directly and get them in here automatically that way and spare us any merging efforts:

http://cgit.freedesktop.org/xorg/app/intel-gpu-tools/

**Comment by maurizio-emmex** [comment]
Hi grembo,
thank you for the fast answer and sorry for my late one. I consider myself an experienced programmer but I am new to the open source word and the partial port of the intel-gpu-tools to FreeBSD was my first work. Now, I don't know how to "patch into intel-gpu-tools directly", I must study how to do it :-).
About intel_backlight, I do not want to duplicate the repository. Thanks to your idea to put it on GitHub is more simple to install in FreeBSD and surely more used.

Regards,
Maurizio

**Comment by grembo** [comment]
Hi Maurizio,

You can find details on how to contribute here:
http://www.freedesktop.org/wiki/GettingInvolved/

It's important to sign up to their mailing list, otherwise your contribution might go unnoticed indefinitely.

It's not as smooth as contributing through github, but if you manage to get your contribution accepted it'll be useful to a much bigger audience than my little repo on github.

Cheers,
Michael

**Comment by grembo** [comment]
Hi Maurizio,

did you have any luck submitting your patches upstream?
- Michael

**Comment by maurizio-emmex** [comment]
2015-07-06 14:53 GMT+02:00 grembo notifications@github.com:

> Hi Maurizio,
> 
> did you have any luck submitting your patches upstream?
> - Michael
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/grembo/intel_backlight_fbsd/pull/1#issuecomment-118845440
> .

Hi Michael,

I am sorry but I haven't submitted the patches because I haven't understood
what mailing should I subscribe and because I lost the interest with the
intel_backlight program. For changing the backlight  in my laptop I have
patched the driver: https://github.com/maurizio-emmex/i915_backlight_freebsd

Regards,
Maurizio

**Comment by grembo** [comment]
Well, that was described on the link I gave you :) But anyway, I'll close this one for now.

**Pull request closed without merging**
